# Generated by Django 2.0.3 on 2018-04-13 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('name', models.CharField(max_length=250)),
                ('key', models.IntegerField(primary_key=True, serialize=False)),
                ('state', models.CharField(max_length=50)),
                ('abbr', models.CharField(max_length=2)),
                ('office', models.CharField(max_length=10)),
                ('party', models.CharField(max_length=50)),
                ('campaign_url', models.CharField(max_length=250)),
                ('bp_url', models.CharField(max_length=250)),
                ('emails', models.CharField(blank=True, max_length=250, null=True)),
                ('facebook', models.CharField(blank=True, max_length=100, null=True)),
                ('twitter', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'candidate',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PrimaryDate',
            fields=[
                ('key', models.IntegerField(primary_key=True, serialize=False)),
                ('state', models.CharField(max_length=50)),
                ('abbr', models.CharField(max_length=2)),
                ('date', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'primarydate',
                'managed': False,
            },
        ),
    ]
